spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    username: root
    password: root
  # The sql.init block was moved from under jpa.properties to here
  sql:
    init:
      mode: always
      continue-on-error: false
  jpa:
    # Set ddl-auto to 'none' to avoid conflicts with schema.sql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
